name: Deploy to Hugging Face
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  STATIC_SPACE: "severo/parquet-viewer"
  DIRECTORY: "dist"

jobs:
  deploy:
    # inspired by https://huggingface.co/blog/severo/build-static-html-spaces
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install huggingface_hub
        run: pip install --upgrade "huggingface_hub[cli]"
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: build the app
        run: npm install && npm run build
      - name: Copy the README.md from the space to the public folder
        run: huggingface-cli download --token=${{ secrets.HF_TOKEN }} --repo-type=space --local-dir=${{env.DIRECTORY}} ${{env.STATIC_SPACE}} README.md
      - name: Delete hfh cache
        run: rm -rf ${{env.DIRECTORY}}/.cache
      - name: Push to HF space (deleting the previous files)
        run: huggingface-cli upload --token=${{ secrets.HF_TOKEN }} --repo-type=space ${{env.STATIC_SPACE}} ${{env.DIRECTORY}} . --delete "*"
